---
version: '3.7'
services:
  maven_custom:
    build: 
      context: ./maven_custom
      dockerfile: Dockerfile
    volumes:
      - .:/usr/local/tomcat
  tomcat:
    image: tomcat:9.0.71-jdk11-temurin-focal
    volumes: 
      - data:/tmp
    ports:
      - 8080:8080
    depends_on:
      - maven_custom
volumes:
  data:
