---
version: '3.7'
services:
  maven:
    build: 
      context: ./maven_custom
      dockerfile: Dockerfile
    volumes:
      - $HOME/.m2/repository:/root/.m2/repository
      - data:/tmp
  tomcat:
    image: tomcat:9.0.71-jdk11-temurin-focal
    volumes: 
      - data:/usr/local/tomcat/
    ports:
      - 8080:8080
    depends_on:
      - maven
volumes:
  data:
