---
version: '3.7'
services:
  maven_custom:
    build: 
      context: ./maven_custom
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: /usr/local/tomcat/boxfuse-sample-java-war-hello/hello-1.0.war
        target: ./data/
  tomcat:
    image: tomcat:9.0.71-jdk11-temurin-focal
    volumes: 
      - type: bind
        source: ./data/hello-1.0.war
        target: /usr/local/tomcat/webapps
    ports:
      - 8080:8080
    depends_on:
      - maven_custom
