---
version: '3.7'
services:
  maven:
    build: 
      context: maven_3.8.7-openjdk/
    volumes:
      - maven_3.8.7-openjdk:/usr/local/tomcat/webapps
  tomcat:
    build: 
      context: tom/
    volumes: 
      - maven_3.8.7-openjdk:/usr/local/tomcat/webapps/hello-1.0
    ports:
      - 8080:8080
    depends_on:
      - maven
volumes:
  maven_3.8.7-openjdk:
