---
# tasks file for tomcat
- name: Ensure install tomcat9
  apt: name={{item}} state=installed
  with_items:
    - tomcat9
  notify:
    - restart tomcat

- name: Copy file
  copy:
     src: 10.129.0.12:/tmp/10.129.0.9/tmp/github/boxfuse-sample-java-war-hello/target/hello-1.0.war
     dest: /var/lib/tomcat9/webapps