---
# tasks file for mvn_n_build
- name: Build java app
  raw: cd {{ git_dir }}/boxfuse-sample-java-war-hello && mvn package

- name: Send *.war file in tomcat host
  synchronize:
    src: /tmp/github/boxfuse-sample-java-war-hello/target/hello-1.0.war
    dest: rsync://10.129.0.25/tmp
  delegate_to: 10.129.0.12