---
- name: install java
  hosts: all
  become: yes

  tasks:
    - name: Ensure default-jdk package is present
      apt:
        name: default-jdk
        state: present

- name: install git and clone repository
  hosts: web
  become: yes

  tasks:
    - name: Ensure git package is present
      apt:
        name: git
        state: present
    
    - name: Clone a github repository
      git:
        repo: https://github.com/Elferey/devops_school.git
        dest: /tmp/github
        clone: yes
        update: yes

- name: install maven and build
  hosts: web
  become: yes

  tasks:
    - name: Ensure maven package is present
      apt:
        name: maven
        state: present

    - name: Build java app
      raw: cd /tmp/github/boxfuse-sample-java-war-hello && mvn package

- name: send hello-1.0.war file in launching server
  hosts: web
  become: yes

  tasks:
    - name: Copy war file in host
      fetch:
        src: /tmp/github/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /tmp

- name: Install tomcat9 in launch server
  hosts: db
  become: yes

  tasks:
    - name: Install tomcat9
      apt:
        name: tomcat9
        state: present

    - name: Ensure nginx service is started
      service:
        name: tomcat9
        state: started

- name: Copy war file in launch server
  hosts: db
  become: yes

  tasks:
    - name: Copy file
      copy:
        src: /tmp/10.129.0.9/tmp/github/boxfuse-sample-java-war-hello/target/
        dest: /var/lib/tomcat/webapps