---
# tasks file for webserver
- name: Ensure nginx packages is present
  apt:
    name: nginx
    state: present

- name: Ensure copy index.html
  copy: src=index.html dest={{ dest_folder }}/index.html mode=0555
  notify:
    - restart nginx
